name: SonarQube Scan
on: [push]

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
    - name: Checking out
      uses: actions/checkout@master
     
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master      
      with: 
        GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
       
