name: SonarQube Scan
on: [push]

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
    - name: Checking out
      uses: actions/checkout@master
     
    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
      with:
       args: -X
         -Dsonar.organization=camila2911
         -Dsonar.projectKey=sonar_test
      env: 
        GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       
